# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - script: npm -v
    displayName: "Npm version"

  - script: yarn
    displayName: "Install dependencies"

  - script: yarn build
    displayName: "Yarn build"

  - script: yarn --production
    displayName: "Prune dependencies"
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1